Repository GodYoungHwan/CPP_PushBox, pull requests merged in 2019-06, with the labels that each got.

#6 Issue#5-Add new functions
  source/CommonDefinition.h
  source/Main.cpp
  source/PushBoxGame.cpp
  source/PushBoxGame.h
  source/level1.txt
  source/level2.txt
  source/level3.txt
  source/level4.txt
  source/level5.txt
Labels: enhancement

#9 making board
  source/Main.cpp
  source/PushBoxGame.h
Labels: enhancement

#11 Issue#10 Adopt ncurses
  .gitignore
  Makefile
  source/CommonDefinition.h
  source/Main.cpp
  source/PushBoxGame.cpp
  source/PushBoxGame.h
Labels: enhancement

#13 add moving function
  source/Main.cpp
  source/PushBoxGame.cpp
  source/PushBoxGame.h
  source/a.out
  source/level1.txt
Labels: enhancement

#15 Issue#14 Refactoring
  .gitignore
  README.md
  source/CommonDefinition.h
  source/GameController.cpp
  source/GameController.h
  source/GameViewer.h
  source/Main.cpp
  source/PushBoxGame.cpp
  source/PushBoxGame.h
  source/a.out
  source/level1.txt
Labels: enhancement, refactoring

#19 Add function to get step and push value and fix bug of goal marker
  .gitignore
  source/GameController.cpp
  source/GameController.h
  source/GameViewer.h
  source/Main.cpp
  source/PushBoxGame.h
Labels: bug, enhancement

#20 Issue#18-Redesign and can go next level
  .gitignore
  source/GameController.cpp
  source/GameController.h
  source/GameViewer.h
  source/Main.cpp
  source/PushBoxGame.h
  source/level2.txt
  source/level3.txt
  source/level4.txt
  source/level5.txt
Labels: enhancement

#22 Issue#21 Connect the variables of classes and show the step and the push
  .gitignore
  source/GameController.cpp
  source/GameController.h
  source/GameViewer.h
  source/Main.cpp
  source/PushBoxGame.h
Labels: enhancement

#24 Issue#23-Show player and fix index error
  source/GameController.cpp
  source/GameController.h
  source/GameViewer.h
  source/Main.cpp
  source/PushBoxGame.h
  source/level1.txt
Labels: enhancement

#27 Issue#25-Make start window and restyle
  source/GameController.cpp
  source/GameController.h
  source/GameViewer.h
  source/Main.cpp
Labels: enhancement

#28 Issue#26-Make result window and Restyle
  source/GameController.cpp
  source/GameController.h
  source/GameViewer.h
  source/Main.cpp
  source/PushBoxGame.h
Labels: enhancement
